### PR TITLE
update ATAG Overview page -- Response to #21

### PR DESCRIPTION
**Pull request by iadawn**

### CODE REVIEW

**Comment by iadawn** [comment]
@shawna-slh worth having a look at the line on remaining relevant?

**Comment by shawna-slh** [comment]
@SteveALee why failed?

**Comment by SteveALee** [comment]
Because using old dependencies before fixing Dependency hell. The trouble with PRs is the target branch (master) is pointing at old version. I tried update master in the PR but doesn't rerun the deploy.

The best solution is to merge master into [iadawn-patch-1](https://github.com/w3c/wai-intro-atag/tree/iadawn-patch-1) to update it. Let me see if can do

**Comment by SteveALee** [comment]
@shawna-slh fixed. I created and merged a new PR in GH to merge master into iadawn-patch-1. You can see it in the history above. The Netlify preview build was triggered automatically by this.

**Pull request merged**
